apiVersion: v1
kind: Service
metadata:
  name: elastichq
  labels:
    name: elastichq
  namespace: ns-elasticsearch
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    name: elastichq
