---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-elasticsearch
  labels:
    name: ns-elasticsearch
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: elastichq
  labels:
    name: elastichq
  namespace: ns-elasticsearch
spec:
  replicas: 1
  selector:
    name: elastichq
  template:
    metadata:
      labels:
        name: elastichq
    spec:
      containers:
        - name: elastichq
          image: elastichq/elasticsearch-hq
          ports:
          - containerPort: 5000
      hostAliases:
        - ip: "10.16.0.25"
          hostnames:
          - "elasticsearch.jyj-nginx.jcloud.com"
