apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebeat
  namespace: ns-elasticsearch
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - image: docker.elastic.co/beats/filebeat:6.4.0
        name: filebeat
        volumeMounts:
        - name: app-logs
          mountPath: /log
        - name: filebeat-config
          mountPath: /etc/filebeat/
      - image: sz-pg-oam-docker-hub-001.tendcloud.com/library/analytics-docker-test:Build_8
        name : app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-logs
          mountPath: /usr/local/TalkingData/logs
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    run: filebeat
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      paths:
        - "/log/*"
        - "/log/usermange/common/*"
    output.elasticsearch:
      hosts: ["elasticsearch-service"]
    index: "filebeat-docker"
