---
apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    app: es-service
spec:
  ports:
  - port: 80
    name: es-port
    targetPort: 9200
  clusterIP: None
  selector:
    app: es
#---
#apiVersion: policy/v1beta1
#kind: PodDisruptionBudget
#metadata:
#  name: es-pdb
#spec:
#  selector:
#    matchLabels:
#      app: es
#  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es
spec:
  serviceName: es-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
      - name: k8ses
        imagePullPolicy: Always
        image: 10.16.0.144:5000/es/es-bdp-private-v1.0:20190508154704
        command: ["bash", "-c", "sysctl -w vm.max_map_count=262144 && exec /export/servers/monit/bin/monit -I"]
        volumeMounts:
        - name: es-datadir
          mountPath: /export/Data
  volumeClaimTemplates:
  - metadata:
      name: es-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: stateful-es-storage-class
      resources:
        requests:
          storage: 500Gi
