---
apiVersion: v1
kind: Namespace
metadata:
  name: jyj-hadoop
  labels:
    name: jyj-hadoop

---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    role: hive
  name: hadoop-hive
  namespace: jyj-hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      role: hive
  template:
    metadata:
      labels:
        role: hive
    spec:
      containers:
        - name: hive
          image: registry.cn-hangzhou.aliyuncs.com/devkevin/hive-diy:v16.0
          command:
            - /root/init.sh
          ports:
            - containerPort: 10000
              protocol: TCP
            - containerPort: 9083
              protocol: TCP
            - containerPort: 10002
              protocol: TCP
          env:
            - name: "NAMENODE_ADDR"
              value: "10.16.0.144"
            - name: "MYSQL_ADDR"
              value: "10.16.0.146"
            - name: "MYSQL_USER"
              value: "root"
            - name: "MYSQL_PASSWD"
              value: "mysql"
            - name: "RESOURCEMANAGER_ADDR"
              value: "10.16.0.144"
            - name: "JOBHISTORY_ADDR"
              value: "10.16.0.146"
            - name: "HADOOP_HOME"
              value: "/home/hadoop/hadoop-2.7.6"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    role: hive
  name: hadoop-hive
  namespace: jyj-hadoop
spec:
  ports:
    - name: tcp
      port: 10000
      targetPort: 10000
    - name: http
      port: 10002
      targetPort: 10002
  selector:
    role: hive
