kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  ports:
  - protocol: TCP
    port: 50070
    targetPort: 50070
---
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service-endpoints
subsets:
  - addresses:
      - ip: 10.16.0.144
    ports:
      - port: 50070