---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stateful-influxdb-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-influxdb-local-pv
  namespace: default
  labels:
    pv: Stateful-influxdb
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-influxdb-storage-class
  local:
    path: /data4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.171

