---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: namenode-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode0-local-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage-class
  local:
    path: /data8
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.144
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode1-local-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage-class
  local:
    path: /data8
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.145
