---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: namenode-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-namenode-local-pv-0
  namespace: default
  labels:
    pv: Stateful-namenode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage-class
  local:
    path: /data5
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.163
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-namenode-local-pv-1
  namespace: default
  labels:
    pv: Stateful-namenode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage-class
  local:
    path: /data8
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.170
