---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stateful-mysql-master-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-mysql-master-local-pv
  namespace: default
  labels:
    pv: Stateful-mysql-master
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-mysql-master-storage-class
  local:
    path: /data5
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.171

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stateful-mysql-slave-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-mysql-slave-local-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-mysql-slave-storage-class
  local:
    path: /data5
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.144
