apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging-new
  namespace: kube-system
  labels:
    k8s-app: kibana-logging-new
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging-new
  template:
    metadata:
      labels:
        k8s-app: kibana-logging-new
    spec:
      containers:
      - name: kibana-logging-new
        image: docker.elastic.co/kibana/kibana:5.6.4
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging-new:9200
          - name: SERVER_BASEPATH
            value: /api/v1/namespaces/kube-system/services/kibana-logging-new/proxy
          - name: XPACK_MONITORING_ENABLED
            value: "true"
          - name: XPACK_SECURITY_ENABLED
            value: "true"
          - name: KIBANA_URL
            value: 0.0.0.0:5601
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
