---
apiVersion: v1
kind: Service
metadata:
  name: bdp-private-zookeeper
  labels:
    app: bdp-private-zookeeper
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: bdp-private-zookeeper-port
  labels:
    app: bdp-private-zookeeper
spec:
  type: NodePort
  ports:
  - port: 2888
    name: server
    targetPort: 2888
    nodePort: 30888
  - port: 3888
    name: leader-election
    targetPort: 3888
    nodePort: 30388
  selector:
    app: zookeeper
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
spec:
  selector:
    matchLabels:
      app: zookeeper
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: bdp-private-zookeeper
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: k8szookeeper
        imagePullPolicy: Always
        image: 10.16.0.144:5000/zookeeper-3.4.11/zookeeper-3.4.11-bdp-private-v1.0:20190523175417
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command: ["/export/servers/monit/bin/monit"]
        args: ["-I"]
        volumeMounts:
        - name: datadir
          mountPath: /export/Data
        resources:
          requests:
            cpu: 4000m
            memory: 10240Mi
          limits:
            cpu: 4000m
            memory: 10240Mi
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: stateful-zookeeper-storage-class
      resources:
        requests:
          storage: 500Gi
