apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: ns-elasticsearch
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      hostAliases:
      - ip: "10.16.0.25"
        hostnames:
        - "elasticsearch.jyj-nginx.jcloud.com"
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.5.4
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://10.16.0.148:9200"
          - name: "KIBANA_BASE_URL"
            value: "/apis/v1/proxy/namespaces/ns-elasticsearch/services/kibana"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: ns-elasticsearch
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana
