---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stateful-datanode-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-datanode-local-pv-0
  namespace: default
  labels:
    pv: Stateful-datanode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-datanode-storage-class
  local:
    path: /data9
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.171
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-datanode-local-pv-1
  namespace: default
  labels:
    pv: Stateful-datanode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-datanode-storage-class
  local:
    path: /data9
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.145
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-datanode-local-pv-2
  namespace: default
  labels:
    pvlabel: Stateful-datanode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stateful-datanode-storage-class
  local:
    path: /data9
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.144
