---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: journalnode-storage-class
  namespace: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: journalnode0-local-pv
  namespace: default
  labels:
    pv: Stateful-journalnode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: journalnode-storage-class
  local:
    path: /data7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.211.27.171
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: journalnode1-local-pv
  namespace: default
  labels:
    pv: Stateful-journalnode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: journalnode-storage-class
  local:
    path: /data7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.144
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: journalnode2-local-pv
  namespace: default
  labels:
    pv: Stateful-journalnode
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: journalnode-storage-class
  local:
    path: /data7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.16.0.145
