---
apiVersion: v1
kind: Namespace
metadata:
  name: jyj-kafka
  labels:
    name: jyj-kafka
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-manager
  labels:
    name: kafka-manager
  namespace: jyj-kafka
spec:
  replicas: 1
  selector:
    name: kafka-manager
  template:
    metadata:
      labels:
        name: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: sheepkiller/kafka-manager
          ports:
          - containerPort: 9000
          env:
          - name: ZK_HOSTS
            value: "10.16.0.144:2181,10.16.0.145:2181,10.16.0.146:2181/jyj-kafka"
      hostAliases:
        - ip: "10.16.0.25"
          hostnames:
          - "elasticsearch.jyj-nginx.jcloud.com"
