apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    name: kafka-manager
  namespace: jyj-kafka
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    name: kafka-manager
